### ISSUE TITLE
Problem whit huge satoshis

### ISSUE THREAD

**Issue by JimScope** [Anderson00/FreeBotCoin#1]
Cuando se tienen altas sumas se pierde casi completamente. hay alguna manera de evitar esto?

**Comment by knoxcard** [comment]
@JimmyAngel23 Translation: When you have high sums you lose almost completely. Is there any way to avoid this?

**Comment by knoxcard** [comment]
@JimmyAngel23: No, creo que es mejor usar siempre el guion y cobrar tal vez alrededor de $ 5 y comenzar todo de nuevo. Esto se debe a que Freebitco.in obviamente hace trampas para que no pierdan grandes sumas de dinero en un momento dado en una cuenta de usuario.

"No, I think it's best to always use the script and cash out maybe around $5 and start all over again.  This is because Freebitco.in obviously cheats hard so they do not lose large sums of money at any given time to one user account."

**Comment by JimScope** [comment]
Having at least for example 2000 satoshis, with this I can not remove them so it is still at risk. Is there a way to set a loss limit, following the example up to 500 satoshis and the script stops?

**Comment by Anderson00** [comment]
Translation Google: Si usted sabe usar javascript podrá configurar márgenes de pérdida y ganancia (No he hecho interfaz gráfica). Si utilizas el BOT en dos ventanas del freebitco.in diferentes (la misma cuenta), es como si se embromar intente!

If you know how to use javascript you will be able to configure loss and gain margins (I did not graph interface). If you use BOT in two different freebitco.in windows (same account), it's as if you cheat the system. Try!
